### PR TITLE
Get `refresh-mirrors.sh` working on ARM

### PR DESCRIPTION
**Pull request by pvshvp-oss**

### CODE REVIEW

**Comment by pvshvp-oss** [comment]
Here is a sample run of the `sed` command: 
```sh
rebornos-arm-docker on  refresh_mirrors_patch [!] 
❯ sed -n 's/\s*Server\s*=\s*//p'  "/etc/pacman.d/reborn-mirrorlist"
http://mirrors.gigenet.com/OSDN/storage/g/r/re/rebornos/repo/RebornOS/
https://mirrors.ocf.berkeley.edu/osdn/storage/g/r/re/rebornos/repo/RebornOS/
http://osdn.mirror.constant.com/storage/g/r/re/rebornos/repo/RebornOS/
http://mirror.math.princeton.edu/pub/osdn/storage/g/r/re/rebornos/repo/RebornOS/
http://pumath.dl.osdn.jp/storage/g/r/re/rebornos/repo/RebornOS/
https://repo.rebornos.org/RebornOS/
https://mirrors.dotsrc.org/osdn/storage/g/r/re/rebornos/repo/RebornOS/
https://plug-mirror.rcac.purdue.edu/osdn/storage/g/r/re/rebornos/repo/RebornOS/
http://194.71.11.163/mirror/osdn.net/storage/g/r/re/rebornos/repo/RebornOS/
http://ftp.openbsd.dk/osdn/storage/g/r/re/rebornos/repo/RebornOS/
http://ftp.dk.xemacs.org/osdn/storage/g/r/re/rebornos/repo/RebornOS/
https://ftp.iij.ad.jp/pub/osdn.jp/storage/g/r/re/rebornos/repo/RebornOS/
https://mirror.clarkson.edu/RebornOS/RebornOS/
https://sourceforge.net/projects/rebornos/files/r/RebornOS/
https://free.nchc.org.tw/osdn/storage/g/r/re/rebornos/repo/RebornOS/
https://ftp.acc.umu.se/mirror/osdn.net/storage/g/r/re/rebornos/repo/RebornOS/
https://ftp.sunet.se/mirror/osdn.net/storage/g/r/re/rebornos/repo/RebornOS/
http://mirroronet.pl/pub/mirrors/sourceforge.jp/storage/g/r/re/rebornos/repo/RebornOS/
https://openbsd.c3sl.ufpr.br/osdn/storage/g/r/re/rebornos/repo/RebornOS/
http://ftp.halifax.rwth-aachen.de/osdn/storage/g/r/re/rebornos/repo/RebornOS/
https://ftp.jaist.ac.jp/pub/sourceforge.jp/storage/g/r/re/rebornos/repo/RebornOS/
```

**Review by Rippanda12 — DISMISSED** [review]
`sed -i 's|$repo/os/$arch/|RebornOS/os/aarch64/RebornOS.files|g' /tmp/mirrorfile` One more sed
then rate
then revert with:
```
sed -i 's|RebornOS/os/aarch64/RebornOS.files|$repo/os/$arch/|g' /tmp/saved
sed -i 's|http|Server = http|g' /tmp/saved
```

**Comment by pvshvp-oss** [comment]
Now the script does 
```sh
sed -n 's|\s*Server\s*=\s*||p' "/etc/pacman.d/reborn-mirrorlist" | sed 's|$repo/os/$arch/|RebornOS/os/aarch64/RebornOS.files|g' | /usr/bin/rate-mirrors --concurrency=8 --per-mirror-timeout="$TIMEOUT" --allow-root --save="$TEMP_FILE" stdin
sed -i 's|RebornOS/os/aarch64/RebornOS.files|$repo/os/$arch/|g' "$TEMP_FILE"
sed -i 's|\s*http|Server = http|g' "$TEMP_FILE" 
```

**Comment by pvshvp-oss** [comment]
Current output:
```
[root@computer rebornos-shared]# cat /etc/pacman.d/reborn-mirrorlist | tail -n 20
# FINISHED AT: 2022-11-27 22:02:33.737288372 +00:00
Server = https://geo.cdn.soulharsh007.rocks/RebornOS-ARM/$repo/os/$arch/
Server = https://pub-236acba899534258ba381237ad7d8714.r2.dev/RebornOS-ARM/$repo/os/$arch/
Server = https://plug-mirror.rcac.purdue.edu/osdn/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = https://mirrors.ocf.berkeley.edu/osdn/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = http://osdn.mirror.constant.com/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = http://mirrors.gigenet.com/OSDN/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = https://mirrors.dotsrc.org/osdn/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = http://mirror.math.princeton.edu/pub/osdn/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = http://ftp.openbsd.dk/osdn/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = http://ftp.dk.xemacs.org/osdn/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = https://ftp.sunet.se/mirror/osdn.net/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = http://194.71.11.163/mirror/osdn.net/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = http://pumath.dl.osdn.jp/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = http://us.cdn.soulharsh007.rocks/RebornOS-ARM/$repo/os/$arch/
Server = http://ftp.halifax.rwth-aachen.de/osdn/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = https://ftp.acc.umu.se/mirror/osdn.net/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = https://de.mirror.rebornos.org/repo/$repo/os/$arch/
Server = https://openbsd.c3sl.ufpr.br/osdn/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
Server = http://mirroronet.pl/pub/mirrors/sourceforge.jp/storage/g/r/re/rebornos/armrepo/$repo/os/$arch/
[root@computer rebornos-shared]# cat /etc/pacman.d/mirrorlist | tail -n 20
#  10. SpeedTestResult { speed: 137.43 KB/s; elapsed: 1.317019552s; connection_time: 157.142666ms } -> http://nj.us.mirror.archlinuxarm.org/
#  11. SpeedTestResult { speed: 127.24 KB/s; elapsed: 885.406236ms; connection_time: 566.832543ms } -> http://jp.mirror.archlinuxarm.org/
#  12. SpeedTestResult { speed: 97.56 KB/s; elapsed: 858.173594ms; connection_time: 530.036205ms } -> http://dk.mirror.archlinuxarm.org/
#  13. SpeedTestResult { speed: 90.18 KB/s; elapsed: 928.369913ms; connection_time: 408.996216ms } -> http://de4.mirror.archlinuxarm.org/
#  14. SpeedTestResult { speed: 77.79 KB/s; elapsed: 1.058283148s; connection_time: 399.315503ms } -> http://hu.mirror.archlinuxarm.org/
# FINISHED AT: 2022-11-27 22:02:45.246614197 +00:00
Server = http://il.us.mirror.archlinuxarm.org/$arch/$repo
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo
Server = http://fl.us.mirror.archlinuxarm.org/$arch/$repo
Server = http://de5.mirror.archlinuxarm.org/$arch/$repo
Server = http://gr.mirror.archlinuxarm.org/$arch/$repo
Server = http://mirror.archlinuxarm.org/$arch/$repo
Server = http://de3.mirror.archlinuxarm.org/$arch/$repo
Server = http://eu.mirror.archlinuxarm.org/$arch/$repo
Server = http://tw.mirror.archlinuxarm.org/$arch/$repo
Server = http://nj.us.mirror.archlinuxarm.org/$arch/$repo
Server = http://jp.mirror.archlinuxarm.org/$arch/$repo
Server = http://dk.mirror.archlinuxarm.org/$arch/$repo
Server = http://de4.mirror.archlinuxarm.org/$arch/$repo
Server = http://hu.mirror.archlinuxarm.org/$arch/$repo
```

**Pull request merged**
